cc_binary(
    name = "01_create_multiple_connections",
    srcs = ["01_create_multiple_connections.cpp"],
    deps = ["//:libevent"],
)

cc_binary(
    name = "02_send_request_on_multiple_connections",
    srcs = ["02_send_request_on_multiple_connections.cpp"],
    deps = ["//:libevent"],
)
